Repository OpenNeuroOrg/openneuro, pull requests merged in 2018-05, with the labels that each got.

#613 Updating validator to 0.26.6
  packages/openneuro-app/package.json
  packages/openneuro-cli/package.json
  packages/openneuro-server/package.json
Labels: enhancement

#609 celery container
  docker-compose.dev.yml
  docker-compose.yml
Labels: review

#621 Updating validator (after fixing deployment issue)
  packages/openneuro-app/package.json
  packages/openneuro-cli/package.json
  packages/openneuro-server/package.json
Labels: enhancement, review

#622 Upload deadlock fix and better CLI progress
  packages/openneuro-cli/src/files.js
  packages/openneuro-server/datalad/dataset.js
  packages/openneuro-server/graphql/resolvers/dataset.js
Labels: review

#625 Don't display deleted draft info when not an owner
  packages/openneuro-app/src/scripts/dataset/dataset.store.js
Labels: review

#626 Updating upath
  yarn.lock
Labels: enhancement, review

#623 Fix sorting of numerical values
  packages/openneuro-app/src/scripts/dashboard/dashboard.datasets.store.js
  packages/openneuro-app/src/scripts/dashboard/dashboard.jobs.store.js
  packages/openneuro-app/src/scripts/dashboard/dashboard.sort.jsx
  packages/openneuro-app/src/scripts/dashboard/dashboard.utils.js
Labels: review

#620 Fix snapshot redirect url
  packages/openneuro-app/src/scripts/dataset/dataset.store.js
  packages/openneuro-server/yarn.lock
Labels: review

#607 Add a catch to revalidate and clear validating tag
  packages/openneuro-app/src/scripts/dataset/dataset.store.js
Labels: review

#631 allow viewing .bidsignore files in the web ui
  packages/openneuro-app/src/scripts/common/partials/file-tree.jsx
Labels: review

#629 CLI: Run validation before creating a dataset.
  packages/openneuro-cli/src/__tests__/datasets.spec.js
  packages/openneuro-cli/src/actions.js
  packages/openneuro-cli/src/datasets.js
  packages/openneuro-cli/src/upload.js
Labels: review

#632 CLI: Use a built version of apollo-client-upload for compatibility.
  packages/openneuro-client/package.json
  packages/openneuro-client/src/client.js
Labels: review

#635 CLI: Show help if no matching command is run
  packages/openneuro-cli/src/cli.js
Labels: review

#638 Flower container for monitoring Celery tasks
  docker-compose.yml
Labels: review

#640 Datalad datasets page
  packages/openneuro-app/config.js
  packages/openneuro-app/package.json
  packages/openneuro-app/src/scripts/common/forms/click-to-edit.jsx
  packages/openneuro-app/src/scripts/common/partials/file-tree.jsx
  packages/openneuro-app/src/scripts/datalad/dataset-page.jsx
  packages/openneuro-app/src/scripts/datalad/fragments/tools/buttons/follow-btn.jsx
  packages/openneuro-app/src/scripts/datalad/fragments/tools/dataset-toolbar.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.actions.js
  packages/openneuro-app/src/scripts/dataset/dataset.content.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.file-display.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.file-edit.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.metadata.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.routes.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.snapshot-loader.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.store.js
  packages/openneuro-app/src/scripts/dataset/tools/index.js
  packages/openneuro-app/src/scripts/dataset/tools/json/jsoneditor.store.js
  packages/openneuro-app/src/scripts/dataset/tools/publish.jsx
  packages/openneuro-app/src/scripts/dataset/tools/snapshot.jsx
  packages/openneuro-app/src/scripts/routes.jsx
  packages/openneuro-app/src/scripts/utils/bids.js
  packages/openneuro-app/src/scripts/utils/datalad.js
  packages/openneuro-app/src/scripts/utils/json-ld.js
  packages/openneuro-client/src/__mocks__/client.js
  packages/openneuro-client/src/__tests__/datasets.spec.js
  packages/openneuro-client/src/client.js
  packages/openneuro-client/src/datasets.js
  packages/openneuro-client/src/files.js
  packages/openneuro-server/config.js
  packages/openneuro-server/datalad/dataset.js
  packages/openneuro-server/graphql/resolvers/dataset.js
  packages/openneuro-server/graphql/resolvers/index.js
  packages/openneuro-server/graphql/schema.js
  packages/openneuro-server/handlers/datalad.js
  packages/openneuro-server/libs/auth.js
  packages/openneuro-server/routes.js
Labels: review

#653 S3 versions
  packages/openneuro-server/datalad/dataset.js
  packages/openneuro-server/graphql/resolvers/dataset.js
  packages/openneuro-server/graphql/resolvers/index.js
  packages/openneuro-server/graphql/schema.js
  packages/openneuro-server/libs/mongo.js
Labels: review

#652 Refactored validations component and caching improvements
  packages/openneuro-app/src/scripts/datalad/validation/validation-panel.jsx
  packages/openneuro-app/src/scripts/datalad/validation/validation-query.jsx
  packages/openneuro-app/src/scripts/datalad/validation/validation-status.jsx
  packages/openneuro-app/src/scripts/datalad/validation/validation.jsx
  packages/openneuro-app/src/scripts/dataset/__tests__/__snapshots__/dataset.validation.spec.jsx.snap
  packages/openneuro-app/src/scripts/dataset/__tests__/dataset.validation.spec.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.content.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.validation.jsx
  packages/openneuro-client/src/__mocks__/client.js
  packages/openneuro-server/datalad/__tests__/dataset.spec.js
  packages/openneuro-server/datalad/dataset.js
  packages/openneuro-server/datalad/draft.js
  packages/openneuro-server/datalad/snapshots.js
  packages/openneuro-server/graphql/resolvers/datalad.js
  packages/openneuro-server/graphql/resolvers/dataset.js
  packages/openneuro-server/graphql/resolvers/index.js
  packages/openneuro-server/graphql/resolvers/issues.js
  packages/openneuro-server/graphql/resolvers/summary.js
  packages/openneuro-server/graphql/schema.js
  packages/openneuro-server/libs/__mocks__/redis.js
  packages/openneuro-server/package.json
  packages/openneuro-server/yarn.lock
  yarn.lock
Labels: review

#655 New job submission limits
  packages/openneuro-app/src/scripts/dataset/run/index.js
  packages/openneuro-app/src/scripts/dataset/tools/index.js
Labels: review

#659 DataLad web uploader
  packages/openneuro-app/src/sass/crn_app/_upload.upload.scss
  packages/openneuro-app/src/scripts/app.jsx
  packages/openneuro-app/src/scripts/common/forms/file-select.jsx
  packages/openneuro-app/src/scripts/common/partials/block-navigation.jsx
  packages/openneuro-app/src/scripts/common/partials/status.jsx
  packages/openneuro-app/src/scripts/datalad/validation/validation-status.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.content.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.statuses.jsx
  packages/openneuro-app/src/scripts/dataset/dataset.store.js
  packages/openneuro-app/src/scripts/dataset/tools/jobs/index.js
  packages/openneuro-app/src/scripts/nav/__tests__/navbar.navmenu.spec.jsx
  packages/openneuro-app/src/scripts/nav/navbar.navmenu.jsx
  packages/openneuro-app/src/scripts/nav/navbar.usermenu.jsx
  packages/openneuro-app/src/scripts/upload/__mocks__/upload.store.js
  packages/openneuro-app/src/scripts/upload/diff.js
  packages/openneuro-app/src/scripts/upload/upload.actions.js
  packages/openneuro-app/src/scripts/upload/upload.disclaimer.jsx
  packages/openneuro-app/src/scripts/upload/upload.error-link.jsx
  packages/openneuro-app/src/scripts/upload/upload.file-tree.jsx
  packages/openneuro-app/src/scripts/upload/upload.file.actions.js
  packages/openneuro-app/src/scripts/upload/upload.file.store.js
  packages/openneuro-app/src/scripts/upload/upload.issues.jsx
  packages/openneuro-app/src/scripts/upload/upload.js
  packages/openneuro-app/src/scripts/upload/upload.jsx
  packages/openneuro-app/src/scripts/upload/upload.progress.jsx
  packages/openneuro-app/src/scripts/upload/upload.rename.jsx
  packages/openneuro-app/src/scripts/upload/upload.resume.jsx
  packages/openneuro-app/src/scripts/upload/upload.select.jsx
  packages/openneuro-app/src/scripts/upload/upload.store.js
  packages/openneuro-app/src/scripts/uploader/upload-button.jsx
  packages/openneuro-app/src/scripts/uploader/upload-disclaimer.jsx
  packages/openneuro-app/src/scripts/uploader/upload-issues.jsx
  packages/openneuro-app/src/scripts/uploader/upload-mutation.js
  packages/openneuro-app/src/scripts/uploader/upload-progress-button.jsx
  packages/openneuro-app/src/scripts/uploader/upload-progress.jsx
  packages/openneuro-app/src/scripts/uploader/upload-rename.jsx
  packages/openneuro-app/src/scripts/uploader/upload-select.jsx
  packages/openneuro-app/src/scripts/uploader/upload-status.jsx
  packages/openneuro-app/src/scripts/uploader/upload-step.jsx
  packages/openneuro-app/src/scripts/uploader/uploader-context.js
  packages/openneuro-app/src/scripts/uploader/uploader-location.js
  packages/openneuro-app/src/scripts/uploader/uploader-modal.jsx
  packages/openneuro-app/src/scripts/uploader/uploader-setup-routes.jsx
  packages/openneuro-app/src/scripts/uploader/uploader-status-routes.jsx
  packages/openneuro-app/src/scripts/uploader/uploader.jsx
  packages/openneuro-app/src/scripts/uploader/xhrfetch.js
  packages/openneuro-app/src/scripts/user/user.store.js
  packages/openneuro-app/src/scripts/utils/getAuth.js
  packages/openneuro-app/src/scripts/validation/validation-results.issues.issue.jsx
  packages/openneuro-app/src/scripts/validation/validation-results.issues.jsx
  packages/openneuro-app/src/scripts/validation/validation-results.jsx
  packages/openneuro-client/package.json
  packages/openneuro-client/src/client.js
  yarn.lock
Labels: review
